language: rust
dist: trusty
sudo: false

# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - gfortran
      - libopenblas-dev

# run builds for all the trains (and more)
rust:
  # - nightly
  # - beta
  # check it compiles on the latest stable compiler
  - stable
  # # and the first stable one (this should be bumped as the minimum
  # # Rust version required changes)
  # - 1.0.0

# Load travis-cargo
before_script:
  - |
      pip install git+https://github.com/tspooner/travis-cargo.git@fix-coveralls --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

# Send coverage reports and upload docs
after_success:
  - |
      travis-cargo --only stable coveralls --no-sudo --verify;

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
