[package]
name = "rsrl"
version = "0.0.0"
authors = ["Tom Spooner <t.spooner@liverpool.ac.uk>"]
license = "MIT"
readme = "README.md"


[dependencies]
log = "0.3"
blas = "0.15"
rand = "0.3"
time = "0.1"
ndarray = "0.9"
indicatif = "0.3"
