[package]
name = "rsrl"
version = "0.0.0"
authors = ["Tom Spooner <t.spooner@liverpool.ac.uk>"]
license = "MIT"
readme = "README.md"

[dependencies]
log = "0.3"
rand = "0.3"
itertools = "0.7"
rusty-machine = "0.5"

serde = "1.0"
serde_json = "1.0"
serde_test = "1.0"
serde_derive = "1.0"

slog = "2.0"
slog-term = "2.3"
slog-async = "2.1"

blas = "0.19"
openblas-src = "0.5"

ndarray = { version = "0.10", features = ["blas", "serde-1"] }

[dev-dependencies]
seahash = "3.0"
